name: Docker Test

on:
  push:
    # Test `develop`
    branches:
      - develop
      #- dev
      #- main

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: mosquitto

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set password and username secrets as environment variables
        run: |
        
          if [ -z "${{ secrets.MTC_PASSWD }}" ]; then 
            echo "Secret MTC_PASSWD is missing!" 
            exit 1 
          fi 
          if [ -z "${{ secrets.MTC_USERNAME }}" ]; then 
            echo "Secret MTC_USERNAME is missing!" 
            exit 1 
          fi 
          if [ -z "${{ secrets.ODS_USERNAME}}" ]; then 
            echo "Secret ODS_USERNAME is missing!" 
            exit 1 
          fi 
          if [ -z "${{ secrets.ODS_PASSWD }}" ]; then 
            echo "Secret ODS_PASSWD is missing!" 
            exit 1 
          fi 
          
            MTC_PASSWD=${{ secrets.MTC_PASSWD }}
            MTC_USERNAME=${{ secrets.MTC_USERNAME }}
            ODS_PASSWD=${{ secrets.ODS_PASSWD }}
            ODS_USERNAME=${{ secrets.ODS_USERNAME }}
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
          
            docker build \
            --no-cache \
            --secret id=MTC_PASSWD,env=MTC_PASSWD \
            --secret id=MTC_USERNAME,env=MTC_USERNAME \
            --secret id=ODS_USERNAME,env=ODS_USERNAME \
            --secret id=ODS_PASSWD,env=ODS_PASSWD . --file Dockerfile
          fi
          
